config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # TODO: add constraints { subdomain: 'api' }
  scope module: :api, defaults: { format: :json } do
    namespace :v1 do
      resources :search, only: %i[] do
        collection do
          get :cuisines
          get :categories
        end
      end
    end
  end

  namespace :admin do
    scope constraints: ->(request) { request.env['warden'].user.try(:admin) || false } do
      mount Sidekiq::Web => '/sidekiq'
    end

    resource :dashboard, only: %i[show]

    resources :tools, only: %i[] do
      collection do
        get  :style_guide
        get  :new_recipe
        post :create_recipe
      end
    end
  end

  resources :recipes, only: %i[] do
    get :my_collection, on: :collection
    get :paginate, on: :collection
  end

  resources :buckets, param: :slug do
    get :paginate, on: :collection
    resources :recipes, except: %i[index] do
      collection do
        post :import
      end
      member do
        get :import_status
        get :download_pdf
      end
    end
  end
  resources :contacts, only: %i[index create] do
    get :paginate, on: :collection
  end
  resources :users, only: %i[] do
    get :account, on: :collection
    patch :update_password, on: :collection
  end

  resources :registrations, only: %i[new create], param: :token do
    get :confirmation, on: :member
  end
  resources :passwords, only: %i[edit], param: :token do
    patch :update_password, on: :member
    collection do
      get :recover
      patch :reset_password
    end
  end

  resource :sessions,  only: %i[new create destroy]
  resource :home,      only: %i[show] do
    collection do
      get :terms
      get :privacy
      get :company
      get :changelog
      get :account_plans
      get :features
    end
  end

  # get '*pages' => redirect('/404.html', status: 302)

  root 'homes#show'
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  include PgSearch::Model
  include FileUploader::Attachment.new(:image)

  belongs_to :bucket, counter_cache: true, touch: true
  belongs_to :user

  has_many :recipe_ingredients,  dependent: :destroy
  has_many :recipe_instructions, dependent: :destroy
  has_many :recipe_cuisines,     dependent: :destroy
  has_many :recipe_categories,   dependent: :destroy
  has_many :cuisines,            through:   :recipe_cuisines,   dependent: :nullify, autosave: true
  has_many :categories,          through:   :recipe_categories, dependent: :nullify, autosave: true

  pg_search_scope :search_for_name,
                  against:            :name,
                  ignoring:           :accents,
                  associated_against: {
                    recipe_ingredients: :name
                  },
                  using:              {
                    tsearch: {
                      dictionary: I18n.t("languages.#{I18n.locale}"),
                      any_word:   true
                    },
                    trigram: {
                      word_similarity: true
                    }
                  }

  accepts_nested_attributes_for :recipe_ingredients,  allow_destroy: true
  accepts_nested_attributes_for :recipe_instructions, allow_destroy: true
  accepts_nested_attributes_for :categories,          allow_destroy: true
  accepts_nested_attributes_for :cuisines,            allow_destroy: true
  accepts_nested_attributes_for :recipe_categories
  accepts_nested_attributes_for :recipe_cuisines

  enum difficulty: %i[very_easy easy medium hard very_hard]

  scope :imported,   -> { where(imported: true) }
  scope :searchable, lambda { |**args|
    Containers::DependencyContainer['queries.recipes.searchable']
      .(
        user:       args[:user],
        bucket:     args[:bucket],
        query:      args[:query],
        options:    args[:options],
        eager_load: args[:eager_load]
      )
  }

  def total_cooking
    return time_calculator.(array: [total_time], options: { format: :short }) if total_time.any?

    time_calculator.(array: [prep_time, cook_time], options: { format: :short })
  end

  def total_prep_cooking
    time_calculator.(array: [prep_time], options: { format: :short })
  end

  def total_cook_cooking
    time_calculator.(array: [cook_time], options: { format: :short })
  end

  def import_attributes
    {
      imported:    imported,
      external:    external,
      id:          id,
      bucket_slug: bucket.slug
    }
  end

  private

  def time_calculator
    Containers::DependencyContainer['services.recipes.time_calculator']
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  include PaginationConcern
  include DependencyImporter[
    'repositories.recipe_repo',
    'operations.recipes.import_operation',
    'operations.recipes.create_operation',
    'operations.recipes.update_operation',
    'operations.recipes.destroy_operation',
    'operations.recipes.download_pdf_operation',
    'services.static_meta_tags'
  ]

  before_action :redirect_to_new_sesseion

  layout false, only: %i[paginate]

  def my_collection
    newest_recipes
    set_meta_tags(**static_meta_tags.(key: :recipes))
  end

  def paginate
    @pagy, @recipes = paginate_resource(:recipes)
  rescue Error::PageError => _e
    @recipes = []
    render nothing: true, status: :no_content && return
  rescue Pagy::OverflowError => _e
    @recipes = []
    render nothing: true, status: :no_content && return
  end

  def new
    show_breadcrumbs
    new_recipe
    set_meta_tags(title: t('views.labels.new').capitalize!)
  end

  def create
    create_operation.(params: prepare_recipes_params, bucket: bucket) do |service|
      service.success do |result|
        redirect_to bucket_recipe_path(bucket.slug, result[:record]), notice: result[:notice]
      end

      service.failure do |error_object|
        show_breadcrumbs
        new_recipe.attributes = error_object[:message][:params]
        render_error(:new, error_object)
      end
    end
  end

  def show
    show_breadcrumbs
    prepare_metatags
    fresh_when(recipe)
  end

  def edit
    edit_breadcrumbs
    prepare_metatags
  end

  def update
    update_operation.(params: prepare_recipes_params, recipe: recipe) do |service|
      service.success do |result|
        redirect_to bucket_recipe_path(bucket.slug, recipe), notice: result[:notice]
      end

      service.failure do |error_object|
        edit_breadcrumbs
        recipe.attributes = error_object[:message][:params]
        render_error(:edit, error_object)
      end
    end
  end

  def import
    import_operation.(params: prepare_recipes_params, bucket: bucket) do |service|
      service.success do |result|
        redirect_to bucket_recipe_path(bucket.slug, result[:record]), notice: result[:notice]
      end

      service.failure do |error_object|
        import_failure(error_object)
        render template: 'buckets/show'
      end
    end
  end

  def import_status
    render json: { imported: recipe.imported }.to_json, status: :created
  end

  def destroy
    destroy_operation.(recipe: recipe) do |service|
      service.success do |result|
        redirect_to bucket_path(bucket.slug), notice: result[:notice]
      end

      service.failure do |errors|
        redirect_to bucket_path(bucket.slug), error: errors[:message]
      end
    end
  end

  def download_pdf
    download_pdf_operation.(recipe: recipe) do |service|
      service.success do |result|
        send_data result[:record], filename: "#{recipe.name}.pdf", type: 'application/pdf', disposition: 'attachment'
      end

      service.failure do |errors|
        redirect_to bucket_recipe_path(bucket.slug, recipe), error: errors[:message]
      end
    end
  end

  private

  def prepare_metatags
    set_meta_tags(
      title:       recipe.name,
      description: recipe.description,
      keywords:    recipe.categories.pluck(:name).join(', ')
    )
  end

  def show_breadcrumbs
    add_breadcrumb t('views.labels.my_buckets'), buckets_path
    add_breadcrumb t('views.labels.bucket'), bucket_path(bucket.slug)
    add_breadcrumb t('views.labels.recipe')
  end

  def edit_breadcrumbs
    add_breadcrumb t('views.labels.my_buckets'), buckets_path
    add_breadcrumb t('views.labels.bucket'), bucket_path(bucket.slug)
    add_breadcrumb t('views.labels.recipe'), bucket_recipe_path(bucket.slug, recipe)
    add_breadcrumb t('views.labels.edit')
  end

  def prepare_recipes_params
    (unsafe_params[:recipe] || {}).tap do |hash|
      hash[:bucket_id] = bucket.id
      hash[:id] = recipe.id if params[:id]
    end
  end

  def import_failure(error_object)
    newest_recipes
    new_recipe

    return flash.now[:error] = error_object[:message] if error_object[:message].is_a?(String)

    @import_failure_dialog ||= true
    @errors ||= error_object[:message] if error_object[:message].is_a?(Hash)
  end

  def newest_recipes
    @recipes ||= recipes_scope.limit(Constants::DEFAULT_PAGINATION_SIZE).offset(0)
    fresh_when(@recipes)
  end

  def bucket
    @bucket ||= current_user.buckets.find_by!(slug: params[:bucket_slug] || params[:slug])
  end

  def recipe
    @recipe ||= bucket.recipes.find(params[:id])
  end

  def new_recipe
    @new_recipe ||= Recipe.new
  end
end

app/helpers/recipe_helper.rb
# frozen_string_literal: true

module RecipeHelper
  def recipe_time_object(recipe, type)
    Containers::DependencyContainer['structs.recipe_time_struct'].new(recipe.__send__(type))
  end

  def recipe_difficulties
    Recipe.difficulties.map do |key, value|
      [t("views.labels.#{key}"), value]
    end
  end

  def imported?(recipe)
    recipe.external && !recipe.imported
  end

  def safe_back_recipe_path(bucket)
    return bucket_path(bucket.slug) if current_page?(request.referer)

    :back
  end
end

app/views/recipes/_form.html.erb
<article>
  <%= render partial: 'shared/breadcrumbs' %>
  <%= render partial: 'shared/form_errors', locals: { errors: @errors } %>
  <section class="recipe__container">
    <%= form_with model: recipe, url: path, method: method do |f| %>
      <div class="flex__row flex__column--mobile">
        <div class="flex__column flex__column--50" data-controller="image-target">
          <%= image_tag default_image(recipe, :medium), alt: recipe.name, data: { target: 'image-target.image' } %>
          <%- if recipe.cached_image_data.present? %>
            <%= f.hidden_field :image, value: recipe.cached_image_data, id: 'file' %>
          <% end %>
          <%= f.file_field :image, data: { action: 'change->image-target#previewImage' }, accept: allowed_image_extensions %>
          <%= f.label :image, t('views.labels.select_image') %>
        </div>

        <div class="flex__column flex__column--50">
          <div class="field">
            <%= f.label t('views.labels.title') %>
            <%= f.text_field :name, autocomplete: :off %>
          </div>
          <div class="field">
            <%= f.label t('views.labels.description') %>
            <%= f.text_area :description, autocomplete: :off, rows: 10 %>
          </div>
        </div>
      </div>

      <div class="flex__column b-margin">
        <h4 class="capitalized">
          <%= t('views.labels.ingredients') %>
        </h4>
        <div class="recipe__steps-container flex__column">
          <%= f.fields_for :recipe_ingredients do |r| %>
            <%= render partial: 'recipes/nested/recipe_ingredients', locals: { r: r } %>
          <% end %>
          <%= add_nested_field(f, :recipe_ingredients) %>
        </div>
      </div>

      <div class="flex__column b-margin">
        <h4 class="capitalized">
          <%= t('views.labels.additional_info') %>
        </h4>
        <div class="flex__row flex__column--mobile">
          <div class="flex__column flex__column--50">
            <div class="field">
              <%= f.label t('views.labels.portions') %>
              <%= f.number_field :servings, value: f.object.servings || 2, autocomplete: :off, step: 1, min: 1 %>
            </div>
            <div class="field">
              <%= f.label t('views.labels.difficulty') %>
              <%= f.select :difficulty, recipe_difficulties, { prompt: t('views.labels.select') }, autocomplete: :off, class: 'full-width' %>
            </div>
          </div>

          <div class="flex__column flex__column--50">
            <div class="flex__row">
              <%= f.fields_for :prep_time, recipe_time_object(recipe, :prep_time) do |t| %>
                <div class="field r-margin--small">
                  <%= t.label t('views.labels.prep_time') %>
                  <%= t.number_field :hours, step: 1, min: 0, list: [12, 33], autocomplete: :off, placeholder: t('views.labels.hours') %>
                </div>
                <div class="field align-s-fe">
                  <%= t.number_field :minutes, step: 1, min: 0, autocomplete: :off, placeholder: t('views.labels.minutes') %>
                </div>
              <% end %>
            </div>

            <div class="flex__row">
              <%= f.fields_for :cook_time, recipe_time_object(recipe, :cook_time) do |t|%>
                <div class="field r-margin--small">
                  <%= t.label t('views.labels.cooking_time') %>
                  <%= t.number_field :hours, step: 1, min: 0, autocomplete: :off, placeholder: t('views.labels.hours') %>
                </div>
                <div class="field align-s-fe">
                  <%= t.number_field :minutes, step: 1, min: 0, autocomplete: :off, placeholder: t('views.labels.minutes') %>
                </div>
              <% end %>
            </div>

            <div class="flex__row">
              <%= f.fields_for :total_time, recipe_time_object(recipe, :total_time) do |t| %>
                <div class="field r-margin--small">
                  <%= t.label t('views.labels.total_time') %>
                  <%= t.number_field :hours, step: 1, min: 0, autocomplete: :off, placeholder: t('views.labels.hours') %>
                </div>
                <div class="field align-s-fe">
                  <%= t.number_field :minutes, step: 1, min: 0, autocomplete: :off, placeholder: t('views.labels.minutes') %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="flex__column b-margin">
        <h4 class="capitalized">
          <%= t('views.labels.categories') %>
        </h4>
        <div class="autocomplete__wrapper b-margin" data-controller="autocomplete" data-autocomplete-resource="categories">
          <div class="flex__row b-margin--small">
            <%= search_field_tag :search, nil,
                                          autocomplete: :off,
                                          placeholder: t('views.labels.search_placeholder'),
                                          data: {
                                            action: 'keypress->autocomplete#submit input->autocomplete#listSuggestions',
                                            target: 'autocomplete.autocompleteField'
                                          }
            %>
            <button type="button"
                    name="button"
                    class="btn__circled btn__circled--small btn__circled__primary btn__circled--plus"
                    data-action="click->autocomplete#submit"
            >
            </button>
          </div>
          <ul class="autocomplete__results" data-target="autocomplete.suggestionsContainer"></ul>
          <ul class="recipe__categories" data-target="autocomplete.tagsContainer">
            <%= f.fields_for :categories do |r| %>
              <%= render partial: 'recipes/nested/categories', locals: { r: r } %>
            <% end %>
          </ul>
          <div id="categoriesChild">
            <%= link_to '#', '#', data: { target: 'autocomplete.cancer', 'nodes': render_assoc(f, :categories) }, class: 'hidden' %>
          </div>
        </div>
      </div>

      <div class="flex__column b-margin">
        <h4 class="capitalized">
          <%= t('views.labels.cuisines') %>
        </h4>
        <div class="autocomplete__wrapper b-margin" data-controller="autocomplete" data-autocomplete-resource="cuisines">
          <div class="flex__row b-margin--small">
            <%= search_field_tag :search, nil,
                                          autocomplete: :off,
                                          placeholder: t('views.labels.search_placeholder'),
                                          data: {
                                            action: 'keypress->autocomplete#submit input->autocomplete#listSuggestions',
                                            target: 'autocomplete.autocompleteField'
                                          }
            %>
            <button type="button"
                    name="button"
                    class="btn__circled btn__circled--small btn__circled__primary btn__circled--plus"
                    data-action="click->autocomplete#submit"
            >
            </button>
          </div>
          <ul class="autocomplete__results" data-target="autocomplete.suggestionsContainer"></ul>
          <ul class="recipe__categories" data-target="autocomplete.tagsContainer">
            <%= f.fields_for :cuisines do |r| %>
              <%= render partial: 'recipes/nested/cuisines', locals: { r: r } %>
            <% end %>
          </ul>
          <div id="cuisinesChild">
            <%= link_to '#', '#', data: { target: 'autocomplete.cancer', 'nodes': render_assoc(f, :cuisines) }, class: 'hidden' %>
          </div>
        </div>
      </div>

      <div class="flex__column b-margin">
        <h4 class="capitalized">
          <%= t('views.labels.steps') %>
        </h4>
        <div class="flex__column recipe__steps-container">
          <%= f.fields_for :recipe_instructions do |r| %>
            <%= render partial: 'recipes/nested/recipe_instructions', locals: { r: r } %>
          <% end %>
          <%= add_nested_field(f, :recipe_instructions) %>
        </div>
      </div>

      <div class="buttons-group">
        <%= f.submit 'Submit', class: 'btn btn__primary' %>
        <%= link_to safe_back_recipe_path(bucket) do %>
          <button type="button" name="button" class="btn btn__secondary">
            <%= t('views.labels.cancel') %>
          </button>
        <% end %>
      </div>
    <% end %>
  </section>
</article>

app/views/recipes/_recipe_item.html.erb
<%- bucket = bucket.blank? ? recipe.bucket : bucket %>

<div class="card__item flex__column"
     data-controller="bucket"
     data-bucket-path="<%= bucket_recipe_path(bucket.slug, recipe) %>"
>
  <div class="flex__column pointer" data-action="click->bucket#openRow">
    <%= image_tag default_image(recipe, :small), alt: recipe.name %>
  </div>
  <div class="flex__column pointer" data-action="click->bucket#openRow">
    <%= recipe.name %>
  </div>
  <%- if current_page?(controller: 'recipes', action: :my_collection) %>
    <div class="flex__column">
      <%= link_to recipe.bucket.name, bucket_path(bucket.slug), class: 'link', 'aria-label': bucket.name %>
    </div>
  <% end %>
  <div class="flex__column align-i-c pointer" data-action="click->bucket#openRow">
    <div class="recipe__icon recipe__icon--ingredients" title="<%= t('views.labels.total_ingredients') %>">
      <%= recipe.recipe_ingredients_count %>
    </div>
    <div class="recipe__icon recipe__icon--time" title="<%= t('views.labels.total_time') %>">
      <%= recipe.total_cooking %>
    </div>
    <%- if recipe.difficulty.present? %>
      <div class=" recipe__icon recipe__icon--level">
        <%= t("views.labels.#{recipe.difficulty}") %>
      </div>
    <% end %>
  </div>
  <div class="flex__row just-c-se">
    <%= link_to download_pdf_bucket_recipe_path(bucket.slug, recipe),
        'aria-label': t('views.labels.download_pdf'),
        data: {
          controller: 'target-window',
          action: 'click->target-window#openWindow'
        } do
    %>
      <div class="btn__circled btn__circled__primary btn__circled--pdf btn__circled--very-small"></div>
    <% end %>
    <%= link_to edit_bucket_recipe_path(bucket.slug, recipe), 'aria-label': t('views.labels.edit') do %>
      <div class="btn__circled btn__circled__primary btn__circled--edit btn__circled--very-small"></div>
    <% end %>
    <%= render partial: 'shared/delete_dialog',
               locals: {
                hash: {
                  form_path: bucket_recipe_path(bucket.slug, recipe),
                  name:      recipe.name
                }
              }
    %>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render partial: 'form',
           locals: {
             recipe: @recipe,
             bucket: @bucket,
             method: :put,
             path:   bucket_recipe_path(@bucket.slug, @recipe)
           }
%>

app/views/recipes/my_collection.html.erb
<article data-controller="search">
  <section class="flex__row b-margin just-c-sb">
    <%= form_with url: my_collection_recipes_path, method: :get, class: 'full-width', html: { data: { action: 'submit->search#validateForm' } } do %>
      <div class="flex__row flex__column--mobile">
        <%= search_field_tag :search, params[:search],
                                      autocomplete: :off,
                                      placeholder: t('views.labels.search_placeholder'),
                                      data: {
                                        target: 'search.input',
                                        action: 'input->search#validate'
                                      }
        %>
        <%= submit_tag t('views.labels.search'), class: 'btn btn__primary align-s-c t-margin--small',
                                                 data: { target: 'search.submit' },
                                                 disabled: 'disabled'
        %>
      </div>
    <% end %>
    <div class="flex__column" data-target="search.filterContainer"></div>
  </section>
  <section class="flex__row flex__column--mobile b-margin just-c-fs">
    <%= link_to t('views.labels.all_buckets'), buckets_path, class: 'link link--underline r-margin' %>
    <%= link_to t('views.labels.clear'), my_collection_recipes_path, class: 'link link--underline r-margin' %>
  </section>
  <section class="cards__container" data-target="search.container">
    <div class="loader spinner paginate__loader spinner--quick hidden " data-target="search.loader"></div>
    <%= render partial: 'recipes/recipe_item', collection: @recipes, as: :recipe, locals: { bucket: nil } %>
  </section>
  <%- if @recipes.size.eql?(Constants::DEFAULT_PAGINATION_SIZE) %>
    <button type="button"
            name="button"
            class="btn btn__primary btn--load-more centered-element"
            data-resource="recipes"
            data-params="<%= params.slice(:search).to_json %>"
            data-page="<%= current_page %>"
            data-target="search.buttonLoader"
            data-action="click->search#retrieveRecords"
    >
      <%= t('views.labels.load_more') %>
    </button>
  <% end %>
</article>

app/views/recipes/new.html.erb
<%= render partial: 'form',
           locals: {
             recipe: @new_recipe,
             bucket: @bucket,
             method: :post,
             path:   bucket_recipes_path(@bucket.slug)
           }
%>

app/views/recipes/paginate.html.erb
<%- @recipes.each do |recipe| %>
  <%- bucket = @bucket.present? ? @bucket : recipe.bucket %>
  <%= render partial: 'recipe_item', locals: { bucket: bucket, recipe: recipe } %>
<% end %>

app/views/recipes/show.html.erb
<article>
  <%= render partial: 'shared/breadcrumbs' %>
  <section class="recipe__container" data-controller="recipe" data-recipe-attributes="<%= @recipe.import_attributes.to_json %>">
    <%- if imported?(@recipe) %>
      <div class="loader spinner"></div>
      <h4 class="text-center">
        <%= t('views.labels.importer_spinner') %>
      </h4>
    <% else %>
      <div class="flex__row just-c-sb">
        <h3 class="capitalized"><%= @recipe.name %></h3>
        <div class="flex__row flex__column--mobile recipe__actions align-i-fs">
          <%= link_to download_pdf_bucket_recipe_path(@bucket.slug, @recipe), data: { controller: 'target-window', action: 'click->target-window#openWindow' }, 'aria-label': t('views.labels.download_pdf') do %>
            <div class="btn__circled btn__circled__primary btn__circled--pdf btn__circled--very-small"></div>
          <% end %>
          <%= link_to edit_bucket_recipe_path(@bucket.slug), 'aria-label': t('views.labels.edit') do %>
            <div class="btn__circled btn__circled__primary btn__circled--edit btn__circled--very-small"></div>
          <% end %>
          <%= render partial: 'shared/delete_dialog',
                     locals: {
                      hash: {
                        form_path: bucket_recipe_path(@bucket.slug, @recipe),
                        name:      @recipe.name
                      }
                    }
          %>
        </div>
      </div>
      <div class="flex__row flex__column--mobile align-i-fs b-margin">
        <div class="flex__column flex__column--50 b-margin">
          <%= image_tag default_image(@recipe, :medium), alt: @recipe.name %>
        </div>
        <div class="flex__column flex__column--50">
          <%- if @recipe.description.present? %>
            <div class="recipe__description">
              <h4 class="capitalized">
                <%= t('views.labels.description') %>
              </h4>
              <%= @recipe.description %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="flex__row flex__column--mobile align-i-fs b-margin">
        <div class="flex__column flex__column--50">
          <h4 class="capitalized">
            <%= t('views.labels.ingredients') %>
          </h4>
          <ul class="recipe__list">
            <%- @recipe.recipe_ingredients.each do |ingredient| %>
              <li><%= ingredient.name %></li>
            <% end %>
          </ul>
        </div>
        <div class="flex__column flex__column--50">
          <h4 class="capitalized">
            <%= t('views.labels.additional_info') %>
          </h4>
          <table class="recipe__additional-information b-margin">
            <thead>
              <tr>
                <th><%= t('views.labels.portions') %></th>
                <th><%= t('views.labels.difficulty') %></th>
                <%- if @recipe.recipe_url.present? %>
                  <th><%= t('views.labels.original_link') %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @recipe.servings %></td>
                <td><%= t("views.labels.#{@recipe.difficulty}") %></td>
                <%- if @recipe.recipe_url.present? %>
                  <td>
                    <%= link_to 'Click', @recipe.recipe_url,
                                        class: 'link link--underline',
                                        'aria-label': t('views.labels.original_link'),
                                        data: {
                                          controller: 'target-window',
                                          action: 'click->target-window#openWindow'
                                        }
                    %>
                  </td>
                <% end %>
              </tr>
            </tbody>
          </table>
          <table class="recipe__additional-information">
            <thead>
              <tr>
                <th><%= t('views.labels.prep_time') %></th>
                <th><%= t('views.labels.cooking_time') %></th>
                <th><%= t('views.labels.total_time') %></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @recipe.total_prep_cooking %></td>
                <td><%= @recipe.total_cook_cooking %></td>
                <td><%= @recipe.total_cooking %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <%- if @recipe.categories.present? %>
        <div class="flex__column">
          <h4 class="capitalized">
            <%= t('views.labels.categories') %>
          </h4>
          <ul class="recipe__categories">
            <%- @recipe.categories.each do |category| %>
              <li><%= category.name.capitalize %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%- if @recipe.cuisines.present? %>
        <div class="flex__column">
          <h4 class="capitalized">
            <%= t('views.labels.cuisines') %>
          </h4>
          <ul class="recipe__categories">
            <%- @recipe.cuisines.each do |cuisine| %>
              <li><%= cuisine.name.capitalize %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex__column">
        <h4 class="capitalized">
          <%= t('views.labels.steps') %>
        </h4>
        <ul class="recipe__steps-container">
          <%- @recipe.recipe_instructions.each do |instruction| %>
            <li><%= instruction.content %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </section>
</article>

app/views/recipes/show.pdf.erb
<article>
  <section class="margin-bottom">
    <h1><%= @recipe.name %></h1>
    <%= image_tag default_image(@recipe, :large) %>
  </section>
  <section class="margin-bottom">
    <table>
      <thead>
        <tr>
          <th><%= t('views.labels.portions').titleize %></th>
          <%- if @recipe.difficulty.present? %>
            <th><%= t('views.labels.difficulty').titleize %></th>
          <% end %>
          <th><%= t('views.labels.total_time').titleize %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @recipe.servings %></td>
          <%- if @recipe.difficulty.present? %>
            <td><%= t("views.labels.#{@recipe.difficulty}") %></td>
          <% end %>
          <td><%= @recipe.total_cooking %></td>
        </tr>
      </tbody>
    </table>
  </section>
  <section class="margin-bottom">
    <%- @recipe.recipe_ingredients.each_slice(5) do |ingredients| %>
      <ul class="horizontal__list">
        <%- ingredients.each do |ingredient| %>
          <li class="horizontal__list__item">
            <%= ingredient.name %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </section>
  <section class="margin-bottom">
    <ol>
      <%- @recipe.recipe_instructions.each do |instruction| %>
        <li class="margin-bottom-small">
          <%= instruction.content %>
        </li>
      <% end %>
    </ol>
  </section>
</article>