config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # TODO: add constraints { subdomain: 'api' }
  scope module: :api, defaults: { format: :json } do
    namespace :v1 do
      resources :search, only: %i[] do
        collection do
          get :cuisines
          get :categories
        end
      end
    end
  end

  namespace :admin do
    scope constraints: ->(request) { request.env['warden'].user.try(:admin) || false } do
      mount Sidekiq::Web => '/sidekiq'
    end

    resource :dashboard, only: %i[show]

    resources :tools, only: %i[] do
      collection do
        get  :style_guide
        get  :new_recipe
        post :create_recipe
      end
    end
  end

  resources :recipes, only: %i[] do
    get :my_collection, on: :collection
    get :paginate, on: :collection
  end

  resources :buckets, param: :slug do
    get :paginate, on: :collection
    resources :recipes, except: %i[index] do
      collection do
        post :import
      end
      member do
        get :import_status
        get :download_pdf
      end
    end
  end
  resources :contacts, only: %i[index create] do
    get :paginate, on: :collection
  end
  resources :users, only: %i[] do
    get :account, on: :collection
    patch :update_password, on: :collection
  end

  resources :registrations, only: %i[new create], param: :token do
    get :confirmation, on: :member
  end
  resources :passwords, only: %i[edit], param: :token do
    patch :update_password, on: :member
    collection do
      get :recover
      patch :reset_password
    end
  end

  resource :sessions,  only: %i[new create destroy]
  resource :home,      only: %i[show] do
    collection do
      get :terms
      get :privacy
      get :company
      get :changelog
      get :account_plans
      get :features
    end
  end

  # get '*pages' => redirect('/404.html', status: 302)

  root 'homes#show'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :buckets
  has_many :recipes
  has_many :contacts

  def reset_token_expired?
    reset_token_lifetime < Time.zone.now
  end

  def show_statistics
    Containers::DependencyContainer['services.users.statistics'].(user: self)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include DependencyImporter[
    'operations.users.inline_update_password_operation',
    'services.static_meta_tags'
  ]

  before_action :redirect_to_new_sesseion, only: %i[account update]

  def account
    prepare_account
    set_meta_tags(**static_meta_tags.(key: :account))
  end

  def update_password
    inline_update_password_operation.(params: unsafe_params, user: current_user) do |service|
      service.success do |result|
        redirect_to "#{account_users_path}#changePassword", notice: result[:notice]
      end

      service.failure do |error_object|
        prepare_account
        render_error(:account, error_object)
      end
    end
  end

  def prepare_account
    @contacts   ||= current_user.contacts.newest.first(Constants::DEFAULT_PAGINATION_SIZE)
    @statistics ||= current_user.show_statistics
  end
end

app/views/users/_reset_password.html.erb
<%= render partial: 'shared/form_errors', locals: { errors: @errors } %>

<%= form_with url: "#{update_password_users_path}#changePassword", method: :patch do |f| %>
  <div class="field">
    <%= f.label t('views.labels.current_password') %>
    <%= f.password_field :current_password, autocomplete: :off, required: true %>
  </div>

  <div class="field">
    <%= f.label t('views.labels.new_password') %>
    <%= f.password_field :password, autocomplete: :off, required: true %>
  </div>

  <div class="field">
    <%= f.label t('views.labels.new_password_confirmation') %>
    <%= f.password_field :password_confirmation, autocomplete: :off, required: true %>
  </div>

  <%= f.submit t('views.labels.confirm'), class: 'btn btn__primary' %>
<% end %>

app/views/users/_statistics.html.erb
<div class="flex__row just-c-sb">
  <h4 class="b-margin--small bold cal-poly-pomona-green"><% "#{t('views.labels.statistics')}:" %></h4>
  <h4 class="bold cal-poly-pomona-green"><%= current_user.nick %></h4>
</div>

<div class="b-margin">
  <%- @statistics[:base].each_pair do |key, value| %>
    <div class="flex__row">
      <span class="account__stat-title bold"><%= t("views.labels.#{key}").capitalize! %></span>
      <span class="account__stat-value"><%= value  %></span>
    </div>
  <% end %>
</div>

<h4 class="b-margin--small bold cal-poly-pomona-green"><%= t('views.labels.favourite_urls') %></h4>
<%- @statistics[:favourite_urls].each do |hash| %>
  <div class="flex__row">
    <span class="account__stat-title bold"><%= hash[:url] %></span>
    <span class="account__stat-value"><%= hash[:size] %></span>
  </div>
<% end %>

app/views/users/account.html.erb
<article data-controller="account">
  <div class="flex__row flex__column--mobile b-margin">
    <%= link_to '#statistics', class: 'account__action align-i-c', data: { action: 'account#selectSection', section: 'statistics' } do %>
      <div class="account__action-wrapper bold"><%= t('views.labels.statistics') %></div>
    <% end %>
    <%= link_to '#changePassword', class: 'account__action align-i-c', data: { action: 'account#selectSection', section: 'changePassword' } do %>
      <div class="account__action-wrapper bold"><%= t('views.labels.change_password') %></div>
    <% end %>
    <%= link_to '#planHistory', class: 'account__action account__action--disabled align-i-c', data: { action: 'account#selectSection', section: 'planHistory' } do %>
      <div class="account__action-wrapper bold"><%= t('views.labels.plan_history') %></div>
    <% end %>
    <%= link_to '#mySupport', class: 'account__action account__action--disabled align-i-c', data: { action: 'account#selectSection', section: 'mySupport' } do %>
      <div class="account__action-wrapper bold"><%= t('views.labels.my_support') %></div>
    <% end %>
  </div>
  <div class="flex__column">
    <div id="statistics" class="flex__column account__action-body b-margin hidden">
      <%= render partial: 'statistics' %>
    </div>
    <div id="changePassword" class="flex__column account__action-body b-margin hidden">
      <%= render partial: 'reset_password' %>
    </div>
    <div id="planHistory" class="flex__column account__action-body b-margin hidden">
      <%= render partial: 'plan' %>
    </div>
    <div id="mySupport" class="flex__column account__action-body b-margin hidden" data-controller="search">
      <div class="account__support-container" data-target="search.container">
        <div class="loader spinner paginate__loader spinner--quick hidden" data-target="search.loader"></div>
        <%= render partial: 'contacts/contact_item', collection: @contacts, as: :contact %>
      </div>

      <%- if @contacts.size.eql?(Constants::DEFAULT_PAGINATION_SIZE) %>
        <button type="button"
                name="button"
                class="btn btn__primary btn--load-more centered-element"
                data-resource="contacts"
                data-params="<%= {}.to_json %>"
                data-page="<%= current_page %>"
                data-target="search.buttonLoader"
                data-action="click->search#retrieveRecords"
        >
          <%= t('views.labels.load_more') %>
        </button>
      <% end %>
    </div>
  </div>
</article>