config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # TODO: add constraints { subdomain: 'api' }
  scope module: :api, defaults: { format: :json } do
    namespace :v1 do
      resources :search, only: %i[] do
        collection do
          get :cuisines
          get :categories
        end
      end
    end
  end

  namespace :admin do
    scope constraints: ->(request) { request.env['warden'].user.try(:admin) || false } do
      mount Sidekiq::Web => '/sidekiq'
    end

    resource :dashboard, only: %i[show]

    resources :tools, only: %i[] do
      collection do
        get  :style_guide
        get  :new_recipe
        post :create_recipe
      end
    end
  end

  resources :recipes, only: %i[] do
    get :my_collection, on: :collection
    get :paginate, on: :collection
  end

  resources :buckets, param: :slug do
    get :paginate, on: :collection
    resources :recipes, except: %i[index] do
      collection do
        post :import
      end
      member do
        get :import_status
        get :download_pdf
      end
    end
  end
  resources :contacts, only: %i[index create] do
    get :paginate, on: :collection
  end
  resources :users, only: %i[] do
    get :account, on: :collection
    patch :update_password, on: :collection
  end

  resources :registrations, only: %i[new create], param: :token do
    get :confirmation, on: :member
  end
  resources :passwords, only: %i[edit], param: :token do
    patch :update_password, on: :member
    collection do
      get :recover
      patch :reset_password
    end
  end

  resource :sessions,  only: %i[new create destroy]
  resource :home,      only: %i[show] do
    collection do
      get :terms
      get :privacy
      get :company
      get :changelog
      get :account_plans
      get :features
    end
  end

  # get '*pages' => redirect('/404.html', status: 302)

  root 'homes#show'
end

app/views/shared/_action_dialog.html.erb
<details data-controller="dialog"
         data-dialog-show-dialog="<%= hash[:show_dialog] %>"
         data-dialog-clean-input="<%= hash[:clean_input] %>"
>
  <summary aria-haspopup="dialog" class="<%= hash[:summary_button_classes] %>"><%= hash[:summary_text] %></summary>
  <div class="dialog__background " data-action="click->dialog#close"></div>
  <div class="dialog__container flex__column just-c-c animate-fade-in fast" role="dialog">
    <button type="button"
            name="button"
            aria-label="close"
            class="btn__circled btn__circled__primary btn__circled--close btn__circled--small absolute-right"
            data-action="click->dialog#close"
    ></button>
    <h3 class="text-center bold">
      <%= hash[:sloga] %>
    </h3>
    <%= form_with model: hash[:resource], url: hash[:form_path], method: hash[:form_method] do |f| %>
      <%- if hash[:show_form_errors] %>
        <%= render partial: 'shared/form_errors', locals: { errors: hash[:errors] } %>
      <% end %>

      <div class="field">
        <%= f.label hash[:input_label] %>
        <%= f.__send__(hash[:input_type], hash[:input_key], data: { target: 'dialog.input' }, required: true, autocomplete: :off) %>
      </div>
      <div class="buttons-wrapper">
        <%= f.submit t('views.labels.save'), class: 'btn btn__primary', 'aria-label': t('views.labels.save') %>
        <button type="button"
                name="<%= t('views.labels.save') %>"
                aria-label="<%= t('views.labels.save') %>"
                class="btn btn__secondary"
                data-action="click->dialog#close"
        >
          <%= t('views.labels.cancel') %>
        </button>
      </div>
    <% end %>
  </div>
</details>

app/views/shared/_breadcrumbs.html.erb
<div class="breadcump">
  <%- breadcrumbs.each do |breadcump| %>
    <span><%= link_to breadcump.name, breadcump.path, class: "link #{('link__disabled' if breadcump.path.blank?)}" %></span>
  <% end %>
</div>

app/views/shared/_captcha.html.erb
<div id="captcha"></div>
<script type="text/javascript">
  var onSubmit = function(token) {
     var submitButton = document.getElementById('submit');

     submitButton.removeAttribute('disabled');
     submitButton.removeAttribute('disabled-with');
   };

   var onloadCallback = function() {
     grecaptcha.render('captcha', {
       'sitekey' : "<%= Credentials[:google, :captcha_web_key] %>",
       'callback' : onSubmit
     });
   };
</script>

app/views/shared/_delete_dialog.html.erb
<details data-controller="dialog">
  <summary class="btn__circled btn__circled__danger btn__circled--remove btn__circled--very-small" aria-haspopup="dialog"></summary>
  <div class="dialog__background " data-action="click->dialog#close"></div>
  <div class="dialog__container danger-warning flex__column just-c-c animate-fade-in fast" role="dialog">
    <button type="button"
            name="close"
            aria-label="close"
            class="btn__circled btn__circled__danger btn__circled--close--red btn__circled--small absolute-right"
            data-action="click->dialog#close"
    ></button>
    <h3 class="text-center bold red-text">
      <%= t('views.labels.delete_warning_slogan', name: hash[:name]) %>
    </h3>
    <div class="buttons-wrapper">
      <%= button_to hash[:form_path], class: 'btn btn__danger', name: t('views.labels.confirm'), 'aria-label': t('views.labels.confirm'), method: :delete do %>
        <%= t('views.labels.confirm') %>
      <% end %>
      <button type="button"
              name="<%= t('views.labels.cancel') %>"
              aria-label="<%= t('views.labels.cancel') %>"
              class="btn btn__secondary--danger"
              data-action="click->dialog#close"
      >
        <%= t('views.labels.cancel') %>
      </button>
    </div>
  </div>
</details>

app/views/shared/_flash.html.erb
<%- %i[error notice].each do |type| %>
  <%- if flash[type] %>
  <div class="flash <%= "flash--#{type}" %>" data-controller="flash" role="notification">
    <div class="icon <%= "icon--#{type}" %>"></div>
    <div class="icon <%= "icon--close-#{type}" %>" data-action="click->flash#close"></div>
    <%= flash[type] %>
  </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="flex__row flex__column--mobile just-c-se footer__wrapper">
    <div class="flex__column">
      <%= link_to root_path, class: 'link', 'aria-label': t('views.labels.app')  do %>
        <%= image_tag asset_pack_path('media/images/svgs/meal.svg'), class: 'icon icon--2x', alt: 'Kitchen Stuff' %>
      <% end %>
    </div>
    <div class="flex__row flex__column--mobile">
      <div class="flex__column r-margin--big">
        <h3 class="bold b-margin--small"><%= t('views.labels.learn_more') %></h3>
        <ul>
          <li><%= link_to t('views.labels.changelog'), changelog_home_path, class: 'link', 'aria-label': t('views.labels.changelog') %></li>
          <li><%= link_to t('views.labels.account_plans'), account_plans_home_path, class: 'link', 'aria-label': t('views.labels.account_plans') %></li>
        </ul>
      </div>
      <div class="flex__column r-margin--big">
        <h3 class="bold b-margin--small"><%= t('views.labels.features') %></h3>
        <ul>
          <li><%= link_to t('views.labels.recipe_importer'), "#{features_home_path}#recipe_importer", class: 'link', 'aria-label': t('views.labels.recipe_importer') %></li>
          <li><%= link_to t('views.labels.buckets'), "#{features_home_path}#buckets", class: 'link', 'aria-label': t('views.labels.buckets') %></li>
          <li><%= link_to t('views.labels.cookbook'), "#{features_home_path}#cookbook", class: 'link', 'aria-label': t('views.labels.cookbook') %></li>
          <li><%= link_to t('views.labels.diet_calendar'), "#{features_home_path}#diet_calendar", class: 'link', 'aria-label': t('views.labels.diet_calendar') %></li>
        </ul>
      </div>
      <div class="flex__column r-margin--big">
        <h3 class="bold b-margin--small"><%= t('views.labels.about') %></h3>
        <ul>
          <li><%= link_to t('views.labels.company'), company_home_path, class: 'link', 'aria-label': t('views.labels.company') %></li>
          <li><%= link_to t('views.labels.contact'), contacts_path, class: 'link', 'aria-label': t('views.labels.contact') %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="flex__row flex__column--mobile just-c-se footer__wrapper">
    <div class="flex__column">
      <h4 class="b-margin--small r-margin">
        Kitchen Stuff Inc. All rights reserved.
      </h4>
    </div>
    <div class="flex__row flex__column--mobile">
      <%= link_to t('views.labels.privacy'), privacy_home_path, class: 'link r-margin', 'aria-label': t('views.labels.privacy') %>
      <%= link_to t('views.labels.terms'), terms_home_path, class: 'link r-margin', 'aria-label': t('views.labels.terms') %>
      <%= link_to '#', class: 'link', 'aria-label': 'twitter' do %>
        <%= image_tag asset_pack_path('media/images/svgs/twitter.svg'), class: 'icon r-margin', alt: 'twitter' %>
      <% end %>
      <%= link_to '#', class: 'link', 'aria-label': 'facebook' do %>
        <%= image_tag asset_pack_path('media/images/svgs/facebook.svg'), class: 'icon r-margin', alt: 'facebook' %>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_form_errors.html.erb
<%- if errors.present? %>
  <ul id="formErrors" class="validation__container">
    <%- errors.each do |key, value| %>
      <%- value.each do |message| %>
        <li><%= "#{key.capitalize} #{message}" %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<nav role="navigation">
  <%= link_to root_path, class: 'nav__link nav__link--root', 'aria-label': t('views.labels.app') do %>
    <span><%= t('views.labels.app') %></span>
  <% end %>
  <%= link_to t('views.labels.app'), root_path, class: 'nav__link--mobile', 'aria-label': t('views.labels.app')  %>

  <ul class="nav__desktop">
    <%- if signed_in? %>
      <li>
        <%= link_to my_collection_recipes_path, class: 'nav__link nav__link--recipes', 'aria-label': t('views.labels.recipes') do %>
          <span><%= t('views.labels.recipes') %></span>
        <% end %>
      </li>
      <li>
        <%= link_to buckets_path, class: 'nav__link nav__link--buckets', 'aria-label': t('views.labels.my_buckets') do %>
          <span><%= t('views.labels.my_buckets') %></span>
        <% end %>
      </li>
      <li>
        <%= link_to account_users_path, class: 'nav__link nav__link--account', 'aria-label': t('views.labels.account') do %>
          <span><%= t('views.labels.account') %></span>
        <% end %>
      </li>
      <li>
        <%= link_to contacts_path, class: 'nav__link nav__link--contact', 'aria-label': t('views.labels.contact') do %>
          <span><%= t('views.labels.contact') %></span>
        <% end %>
      </li>
      <li>
        <%= button_to sessions_path, class: 'nav__link nav__link--form nav__link--sign-out', method: :delete, 'aria-label': t('views.labels.logout') do %>
          <span><%= t('views.labels.logout') %></span>
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to features_home_path, class: 'nav__link nav__link--features', 'aria-label': t('views.labels.features') do %>
          <span><%= t('views.labels.features') %></span>
        <% end %>
      </li>
      <li>
        <%= link_to new_registration_path, class: 'nav__link nav__link--register', 'aria-label': t('views.labels.signup') do %>
          <span><%= t('views.labels.signup') %></span>
        <% end %>
      </li>
      <li>
        <%= link_to new_sessions_path, class: 'nav__link nav__link--sign-in', 'aria-label': t('views.labels.login') do %>
          <span><%= t('views.labels.login') %></span>
        <% end %>
      </li>
      <li>
        <%= link_to contacts_path, class: 'nav__link nav__link--contact', 'aria-label': t('views.labels.contact') do %>
          <span><%= t('views.labels.contact') %></span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <details class="nav__mobile"
           data-controller="nav-mobile"
           data-action="click@window->nav-mobile#closeNav touchmove@window->nav-mobile#closeNav"
  >
    <summary></summary>
    <details-menu role="menu">
      <%- if signed_in? %>
        <li role="menuitem"><%= link_to t('views.labels.recipes'), my_collection_recipes_path, 'aria-label': t('views.labels.recipes') %></li>
        <li role="menuitem"><%= link_to t('views.labels.my_buckets'), buckets_path, 'aria-label': t('views.labels.my_buckets') %></li>
        <li role="menuitem"><%= link_to t('views.labels.account'), account_users_path, 'aria-label': t('views.labels.account') %></li>
        <li role="menuitem"><%= link_to t('views.labels.contact'), contacts_path, 'aria-label': t('views.labels.contact') %></li>
        <li role="menuitem"><%= button_to t('views.labels.logout'), sessions_path, method: :delete, 'aria-label': t('views.labels.logout') %></li>
      <% else %>
        <li role="menuitem"><%= link_to t('views.labels.features'), features_home_path, 'aria-label': t('views.labels.features') %></li>
        <li role="menuitem"><%= link_to t('views.labels.signup'), new_registration_path, 'aria-label': t('views.labels.signup') %></li>
        <li role="menuitem"><%= link_to t('views.labels.login'), new_sessions_path, 'aria-label': t('views.labels.login') %></li>
        <li role="menuitem"><%= link_to t('views.labels.contact'), contacts_path, 'aria-label': t('views.labels.contact') %></li>
      <% end %>
    </details-menu>
  </details>
</nav>

app/views/shared/_scroll_button.html.erb
<button type="button"
        name="scrollButton"
        aria-label="<%= t('views.labels.scroll_button') %>"
        class="btn btn__primary btn__scroll"
        data-controller="scroll-button"
        data-action="click->scroll-button#scrollUp"
>
  <%= image_tag asset_pack_path('media/images/svgs/arrow-alt-circle-up.svg'), alt: t('views.labels.scroll_button'), loading: 'lazy' %>
</button>