config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # TODO: add constraints { subdomain: 'api' }
  scope module: :api, defaults: { format: :json } do
    namespace :v1 do
      resources :search, only: %i[] do
        collection do
          get :cuisines
          get :categories
        end
      end
    end
  end

  namespace :admin do
    scope constraints: ->(request) { request.env['warden'].user.try(:admin) || false } do
      mount Sidekiq::Web => '/sidekiq'
    end

    resource :dashboard, only: %i[show]

    resources :tools, only: %i[] do
      collection do
        get  :style_guide
        get  :new_recipe
        post :create_recipe
      end
    end
  end

  resources :recipes, only: %i[] do
    get :my_collection, on: :collection
    get :paginate, on: :collection
  end

  resources :buckets, param: :slug do
    get :paginate, on: :collection
    resources :recipes, except: %i[index] do
      collection do
        post :import
      end
      member do
        get :import_status
        get :download_pdf
      end
    end
  end
  resources :contacts, only: %i[index create] do
    get :paginate, on: :collection
  end
  resources :users, only: %i[] do
    get :account, on: :collection
    patch :update_password, on: :collection
  end

  resources :registrations, only: %i[new create], param: :token do
    get :confirmation, on: :member
  end
  resources :passwords, only: %i[edit], param: :token do
    patch :update_password, on: :member
    collection do
      get :recover
      patch :reset_password
    end
  end

  resource :sessions,  only: %i[new create destroy]
  resource :home,      only: %i[show] do
    collection do
      get :terms
      get :privacy
      get :company
      get :changelog
      get :account_plans
      get :features
    end
  end

  # get '*pages' => redirect('/404.html', status: 302)

  root 'homes#show'
end

app/models/bucket.rb
# frozen_string_literal: true

class Bucket < ApplicationRecord
  include PgSearch::Model

  belongs_to :user

  has_many :recipes, dependent: :destroy

  pg_search_scope :search_for_name,
                  against:  :name,
                  ignoring: :accents,
                  using:    {
                    tsearch: {
                      dictionary: I18n.t("languages.#{I18n.locale}"),
                      any_word:   true
                    },
                    trigram: {
                      word_similarity: true
                    }
                  }

  scope :searchable, lambda { |**args|
    Containers::DependencyContainer['queries.buckets.searchable']
      .(
        user:       args[:user],
        query:      args[:query],
        options:    args[:options],
        eager_load: args[:eager_load]
      )
  }
end

app/controllers/buckets_controller.rb
# frozen_string_literal: true

class BucketsController < ApplicationController
  include PaginationConcern
  include DependencyImporter[
    'repositories.bucket_repo',
    'repositories.recipe_repo',
    'operations.buckets.create_operation',
    'operations.buckets.update_operation',
    'operations.buckets.destroy_operation',
    'services.static_meta_tags'
  ]

  before_action :redirect_to_new_sesseion
  before_action :newest_buckets, except: %i[show paginate]

  layout false, only: %i[paginate]

  def index
    new_bucket
    set_meta_tags(**static_meta_tags.(key: :buckets))
  end

  def paginate
    @pagy, @buckets = paginate_resource(:buckets)
  rescue Error::PageError => _e
    @buckets = []
    render nothing: true, status: :no_content && return
  rescue Pagy::OverflowError => _e
    @buckets = []
    render nothing: true, status: :no_content && return
  end

  def show
    fresh_when(bucket)
    show_breadcrumbs
    new_recipe
    newest_recipes
    set_meta_tags(title: bucket.name)
  end

  def create
    create_operation.(params: prepare_bucket_params, user: current_user) do |service|
      service.success do |result|
        redirect_to bucket_path(slug: result[:record].slug), notice: result[:notice]
      end

      service.failure do |error_object|
        new_bucket.attributes = unsafe_params[:bucket]
        @create_failure_dialog ||= true
        render_error(:index, error_object)
      end
    end
  end

  def update
    update_operation
      .(params: prepare_bucket_params, bucket: bucket) do |service|
      service.success do |result|
        redirect_to bucket_path(slug: result[:record].slug), notice: result[:notice]
      end

      service.failure do |error_object|
        @update_failure_bucket_id ||= bucket.id
        new_bucket
        render_error(:index, error_object)
      end
    end
  end

  def destroy
    destroy_operation.(bucket: bucket) do |service|
      service.success do |result|
        redirect_to buckets_path, notice: result[:notice]
      end

      service.failure do |error_object|
        redirect_to buckets_path, error: error_object[:message]
      end
    end
  end

  private

  def show_breadcrumbs
    add_breadcrumb t('views.labels.my_buckets'), buckets_path
    add_breadcrumb t('views.labels.bucket')
  end

  def prepare_bucket_params
    (unsafe_params[:bucket] || {}).tap do |hash|
      hash[:user_id] = current_user.id
      hash[:id]      = bucket.id if params[:slug]
    end
  end

  def newest_buckets
    @buckets ||= buckets_scope.limit(Constants::DEFAULT_PAGINATION_SIZE).offset(0)
    fresh_when(@buckets)
  end

  def newest_recipes
    @recipes ||= recipes_scope.limit(Constants::DEFAULT_PAGINATION_SIZE).offset(0)
    fresh_when(@recipes)
  end

  def bucket
    @bucket ||= current_user.buckets.find_by!(slug: params[:slug])
  end

  def new_recipe
    @new_recipe ||= Recipe.new
  end

  def new_bucket
    @new_bucket ||= current_user.buckets.new
  end
end

app/views/buckets/_bucket_item.html.erb
<div class="card__item flex__column">
  <div class="flex__row just-c-sb">
    <h4 title="#{bucket.name}" class="bucket__title">
      <%= truncate(bucket.name, length: 20) %>
    </h4>
    <div class="flex__row align-i-fs">
      <%= render partial: 'shared/action_dialog',
                 locals: {
                   hash: {
                     sloga:                  t('views.labels.edit_bucket_slogan', name: bucket.name),
                     summary_button_classes: 'btn__circled btn__circled__primary btn__circled--edit btn__circled--very-small',
                     summary_text:           nil,
                     resource:               bucket,
                     form_path:              bucket_path(slug: bucket.slug),
                     form_method:            :patch,
                     show_form_errors:       true,
                     errors:                 (@errors if @update_failure_bucket_id.try(:eql?, bucket.id)),
                     input_label:            t('views.labels.bucket_name'),
                     input_type:             :text_field,
                     input_key:              :name,
                     clean_input:            false,
                     show_dialog:            @update_failure_bucket_id.try(:eql?, bucket.id) || false
                   }
                 }
      %>
      <%= render partial: 'shared/delete_dialog',
                 locals: {
                  hash: {
                    form_path: bucket_path(bucket.slug),
                    name:      bucket.name
                  }
                }
      %>
    </div>
  </div>
  <div class="flex__column relative">
    <div class="badge relative">
      <div class="badge__body bold">
        <%= t('views.labels.total', type: :recipes, count: bucket.recipes_count) %>
      </div>
      <%= bucket.recipes_count %>
    </div>
    <%= link_to bucket_path(slug: bucket.slug) do %>
      <%= image_tag asset_pack_path('media/images/svgs/empty-meal.svg'), class: 'bucket__background', loading: 'lazy', alt: 'bucket' %>
    <% end %>
  </div>
</div>

app/views/buckets/index.html.erb
<article data-controller="bucket search">
  <%- if @buckets.blank? && params[:search].blank? %>
    <div class="heading-container centered-element">
      <h1 class="aligned-center heading-space--big">
        <%= sanitize(t('views.labels.empty_collection_slogan', path: asset_pack_path('media/images/svgs/frown.svg'))) %>
      </h1>
      <%= render partial: 'shared/action_dialog',
                 locals: {
                   hash: {
                     sloga:                  t('views.labels.new_bucket_dialog_slogan'),
                     summary_button_classes: 'btn btn__primary',
                     summary_text:           t('views.labels.first_bucket'),
                     resource:               @new_bucket,
                     form_path:              buckets_path,
                     form_method:            :post,
                     show_form_errors:       true,
                     errors:                 (@errors if @create_failure_dialog),
                     input_label:            t('views.labels.bucket_name'),
                     input_type:             :text_field,
                     input_key:              :name,
                     clean_input:            true,
                     show_dialog:            @create_failure_dialog
                   }
                 }
      %>
    </div>
  <% else %>
    <section class="flex__row b-margin just-c-sb">
      <%= form_with url: buckets_path, method: :get, class: 'full-width', html: { data: { action: 'submit->search#validateForm' } } do %>
        <div class="flex__row flex__column--mobile">
          <%= search_field_tag :search,
                               params[:search],
                               autocomplete: :off,
                               placeholder: t('views.labels.search_placeholder'),
                               data: { target: 'search.input', action: 'input->search#validate' }
          %>
          <%= submit_tag t('views.labels.search'),
                         class: 'btn btn__primary align-s-c t-margin--small r-margin--small',
                         data: { target: 'search.submit' },
                         disabled: 'disabled'
          %>
        </div>
      <% end %>
      <div class="t-margin--small">
        <%= render partial: 'shared/action_dialog',
                   locals: {
                     hash: {
                       sloga:                  t('views.labels.new_bucket_dialog_slogan'),
                       summary_button_classes: 'btn__circled btn__circled__primary btn__circled--plus',
                       summary_text:           nil,
                       resource:               @new_bucket,
                       form_path:              buckets_path,
                       form_method:            :post,
                       show_form_errors:       true,
                       errors:                 (@errors if @create_failure_dialog),
                       input_label:            t('views.labels.bucket_name'),
                       input_type:             :text_field,
                       input_key:              :name,
                       clean_input:            true,
                       show_dialog:            @create_failure_dialog
                     }
                   }
        %>
      </div>
    </section>
    <section class="flex__row b-margin just-c-fs">
      <%= link_to t('views.labels.all_recipes'), my_collection_recipes_path, class: 'link link--underline r-margin' %>
      <%= link_to t('views.labels.clear'), buckets_path, class: 'link link--underline r-margin' %>
    </section>
    <section class="cards__container" data-target="search.container">
      <div class="loader spinner paginate__loader spinner--quick hidden" data-target="search.loader"></div>
      <%= render partial: 'bucket_item', collection: @buckets, as: :bucket %>
    </section>
    <%- if @buckets.size.eql?(Constants::DEFAULT_PAGINATION_SIZE) %>
      <button type="button"
              name="button"
              class="btn btn__primary btn--load-more centered-element"
              data-resource="buckets"
              data-page="<%= current_page %>"
              data-params="<%= params.slice(:search).to_json %>"
              data-target="search.buttonLoader"
              data-action="click->search#retrieveRecords"
      >
        <%= t('views.labels.load_more') %>
      </button>
    <% end %>
  <% end %>
</article>

app/views/buckets/paginate.html.erb
<%= render partial: 'bucket_item', collection: @buckets, as: :bucket %>

app/views/buckets/show.html.erb
<article data-controller="search">
  <%- if @recipes.blank? && params[:search].blank? %>
    <%= render partial: 'shared/breadcrumbs' %>

    <div class="heading-container centered-element">
      <h1 class="aligned-center heading-space--big">
        <%= sanitize(t('views.labels.empty_collection_slogan', path: asset_pack_path('media/images/svgs/frown.svg'))) %>
      </h1>
      <%= link_to t('views.labels.create_first_reicpe'), new_bucket_recipe_path(@bucket.slug), class: 'btn btn__primary', 'aria-label': t('views.labels.new') %>
      <h1>
        <%= t('views.labels.or') %>
      </h1>
      <%= render partial: 'shared/action_dialog',
                 locals: {
                   hash: {
                     sloga:                  t('views.labels.import_slogan'),
                     summary_button_classes: 'btn btn__primary',
                     summary_text:           t('views.labels.import_recipe'),
                     resource:               @new_recipe,
                     form_path:              import_bucket_recipes_path(@bucket.slug),
                     form_method:            :post,
                     show_form_errors:       true,
                     errors:                 @errors,
                     input_label:            t('views.labels.url'),
                     input_type:             :url_field,
                     input_key:              :url,
                     clean_input:            true,
                     show_dialog:            @import_failure_dialog
                   }
                 }
      %>
    </div>
  <% else %>
    <%= render partial: 'shared/breadcrumbs' %>
    <section class="flex__row flex__column--mobile">
      <div class="flex__row b-margin just-c-sb bucket__search-size flex__column--mobile align-i-c">
        <h4 class="t-margin--small" title="<%= @bucket.name%> "><%= @bucket.name %></h4>
        <%= form_with url: bucket_path(@bucket.slug), method: :get, class: 'full-width', html: { data: { action: 'submit->search#validateForm' } } do %>
          <div class="flex__row flex__column--mobile">
            <%= search_field_tag :search,
                                 params[:search],
                                 autocomplete: :off,
                                 placeholder: t('views.labels.search_placeholder'),
                                 data: { target: 'search.input', action: 'input->search#validate' }
            %>
            <%= submit_tag t('views.labels.search'),
                           class: 'btn btn__primary align-s-c t-margin--small r-margin--small',
                           data: { target: 'search.submit' },
                           disabled: 'disabled'
            %>
          </div>
        <% end %>
      </div>
      <div class="flex__row b-margin just-c-c bucket__search-options t-margin--small">
        <%= render partial: 'shared/action_dialog',
                   locals: {
                     hash: {
                       sloga:                  t('views.labels.import_slogan'),
                       summary_button_classes: 'btn__circled btn__circled__primary btn__circled--import',
                       summary_text:           nil,
                       resource:               @new_recipe,
                       form_path:              import_bucket_recipes_path(@bucket.slug),
                       form_method:            :post,
                       show_form_errors:       true,
                       errors:                 @errors,
                       input_label:            t('views.labels.url'),
                       input_type:             :url_field,
                       input_key:              :url,
                       clean_input:            true,
                       show_dialog:            @import_failure_dialog
                     }
                   }
        %>
        <%= link_to new_bucket_recipe_path(@bucket.slug) do %>
          <div class="btn__circled btn__circled__primary btn__circled--plus"></div>
        <% end %>
      </div>
    </section>
    <section class="flex__row b-margin just-c-fs">
      <%= link_to t('views.labels.clear'), bucket_path(@bucket.slug), class: 'link link--underline r-margin' %>
    </section>
    <section class="cards__container" data-target="search.container">
      <div class="loader spinner paginate__loader spinner--quick hidden" data-target="search.loader"></div>
      <%= render partial: 'recipes/recipe_item', collection: @recipes, as: :recipe, locals: { bucket: @bucket } %>
    </section>
    <%- if @recipes.size.eql?(Constants::DEFAULT_PAGINATION_SIZE) %>
      <button type="button"
              name="button"
              class="btn btn__primary btn--load-more centered-element"
              data-resource="recipes"
              data-params="<%= params.slice(:search, :slug).to_json %>"
              data-page="<%= current_page %>"
              data-target="search.buttonLoader"
              data-action="click->search#retrieveRecords"
      >
        <%= t('views.labels.load_more') %>
      </button>
    <% end %>
  <% end %>
</article>